### ISSUE TITLE
Update this for Swift?

### ISSUE THREAD

**Issue by nehayward** [JohnSundell/CloudKitChat#1]
It'd be really cool to see you update this to swift.

**Comment by JohnSundell** [comment]
@nehayward Thanks for the suggestion, but this repository was only a demo that I used during one of my talks about CloudKit a few years ago, so I'm not going to update it. In fact, I'll archive this so it won't cause confusion, since it's not a maintained project or anything. But hopefully I'll have time to open source some other example application that uses CloudKit in Swift at some later point.
